name: Scrape and Save Data
#steps
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bs4 requests pandas dicttoxml tabulate xmltodict
      - name: Run Script
        run: python app.py

      - name: Commit and Push
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: "Update data"
          add: "./*"
